.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xsn_qt test_xsn_qt
clean: FORCE
	$(MAKE) -C .. xsn_qt_clean test_xsn_qt_clean
check: FORCE
	$(MAKE) -C .. test_xsn_qt_check
xsn-qt xsn-qt.exe: FORCE
	 $(MAKE) -C .. xsn_qt
